##################################################  
################  COMMON ENTITIES  ###############  
##################################################  



###############  input_boolean:  #################  
input_boolean:
  lock_notifications:
    name: "Lock Notifications"

###################  sensor:  ####################  
sensor:

- platform: template
  sensors:

    frontdoor_statusreport:
      friendly_name: 'Front Status Report'
      value_template: >
          {% set number = states('sensor.front_door_lock_alarm_level') %}
          {% set alarm_type_value = states('sensor.front_door_lock_alarm_type') %}
          
          {% set alarm_type_general_actions = {
            '0':'No Status Reported',          
            '9':'Lock Jammed',
            '17':'Keypad Lock Jammed',
            '21':'Manual Lock',
            '22':'Manual Unlock',
            '23':'HA Lock Jammed',
            '24':'HA Lock',
            '25':'HA Unlock',
            '26':'Auto Lock Jammed',
            '27':'Auto Lock',
            '32':'All Codes Deleted',
            '161':'Bad Code Entered',
            '167':'Battery Low',
            '168':'Battery Critical',
            '169':'Battery Too Low To Operate Lock' } %}
          {% set alarm_type_lock_actions = {
            '18':'Keypad Lock',
            '19':'Keypad Unlock',
            '162':'Lock Code Attempt Outside of Schedule' } %}
          {% set alarm_type_code_actions = {
            '33':'Code Deleted',
            '112':'Code Changed',
            '113':'Duplicate Code' } %}
          {% if alarm_type_value in alarm_type_code_actions %}
            {{alarm_type_value}};{{ alarm_type_code_actions[alarm_type_value] }};{{number}}
          {% elif alarm_type_value in alarm_type_lock_actions  %}
            {{alarm_type_value}};{{ alarm_type_lock_actions[alarm_type_value] }};{{number}}
          {% elif alarm_type_value in alarm_type_general_actions %}
            {{alarm_type_value}};{{ alarm_type_general_actions[alarm_type_value] }}
          {% else %}
            {{-1}};Unknown Alarm Type Value {{ states('sensor.front_door_lock_alarm_type') }}
          {% endif %}

###################  automation:  ####################  
automation:
    - alias: User Lock Notifications
      trigger:
        platform: state
        entity_id: sensor.frontdoor_statusreport
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set report = states.sensor.frontdoor_statusreport.state %}
            {% set a = report.split(';') %}
            {% if (a|length) == 3 and (a[2] | int > 0) %} 
              {{ true }}
            {% else %}
              {{ false }}
            {% endif %}
        - condition: template
          value_template: >-
            {% set report = states.sensor.frontdoor_statusreport.state %}
            {% set a = report.split(';') %}
            {% set entity_id = 'frontdoor_notify_' + a[2] %}
            {% set notify = states['input_boolean'][entity_id].state %}
            {{ notify == "on" }}
      action:
        - service: script.conditional_notify
          data_template:
            boolean: input_boolean.lock_notifications
            title: >- 
              {% set report = states.sensor.frontdoor_statusreport.state %}
              {% set a = report.split(';') %}
              {{ a[1] }}
            message: >-
              {% set report = states.sensor.frontdoor_statusreport.state %}
              {% set a = report.split(';') %}
              {% set entity_id = 'input_text.frontdoor_name_' + a[2] %}
              {% set user = states(entity_id) %}
              {{ user }}

###############################
    - alias: Add Code
      trigger:
        entity_id: binary_sensor.frontdoor_active_1, binary_sensor.frontdoor_active_2, binary_sensor.frontdoor_active_3, binary_sensor.frontdoor_active_4, binary_sensor.frontdoor_active_5, binary_sensor.frontdoor_active_6 
        platform: state
        to: 'on'
      action:
        - service: lock.set_usercode
          data_template:
            node_id: >- 
                {{states.zwave.front_door_lock.attributes.node_id}}
            code_slot: >-
                {% set object_id = trigger.to_state.object_id %}
                {% set index = 17 %}
                {% set code_slot = object_id[index:] %}
                {{ code_slot  }}
            usercode: >-
                {% set object_id = trigger.to_state.object_id %}
                {% set index = 17 %}
                {% set code_slot = object_id[index:] %}    
                {% set codetext = 'frontdoor_pin_' + code_slot | string %}
                {% set code = states['input_text'][codetext].state %}
                {{ code | string }}
    
    - alias: Update Code
      trigger:
        entity_id: input_text.frontdoor_pin_1, input_text.frontdoor_pin_2, input_text.frontdoor_pin_3, input_text.frontdoor_pin_4, input_text.frontdoor_pin_5, input_text.frontdoor_pin_6
        platform: state
      condition:
        - condition: template
          value_template: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set index = 14 %}
            {% set code_slot = object_id[index:] %}
            {% set b = 'input_boolean.frontdoor_enabled_' + code_slot | string %}
            {{ is_state(b, 'on') and (trigger.from_state.state != trigger.to_state.state)}}
      action:
        - service: persistent_notification.create
          data_template:
            title: "LOCK MANAGER"
            message: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set index = 14 %}
              {% set code_slot = object_id[index:] %}
              {{ 'You changed the PIN for code  ' + code_slot | string + '. Please enable it in order to make it active.'}}
        - service: input_boolean.turn_off
          data_template:
            entity_id: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set index = 14 %}
              {% set code_slot = object_id[index:] %}
              {{ 'input_boolean.frontdoor_enabled_' + code_slot | string }}
    
    - alias: Clear Code
      trigger:
        entity_id: binary_sensor.frontdoor_active_1, binary_sensor.frontdoor_active_2, binary_sensor.frontdoor_active_3, binary_sensor.frontdoor_active_4,binary_sensor.frontdoor_active_5, binary_sensor.frontdoor_active_6 
        platform: state
        to: 'off'
      action:
        # - service: lock.clear_usercode
        #   data_template:
        #     node_id: >- 
        #         {{states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked_frontdoor.attributes.node_id}}
        #     code_slot: >-
        #         {% set object_id = trigger.to_state.object_id %}
        #         {% set index = 17 %}
        #         {% set code_slot = object_id[inex:] %}
        #         {{ code_slot  }}
        - service: lock.set_usercode
          data_template:
            node_id: >- 
              {{states.lock.schlage_allegion_be469_touchscreen_deadbolt_locked_frontdoor.attributes.node_id}}
            code_slot: >-
              {% set index = 17 %}
              {% set object_id = trigger.to_state.object_id %}
              {% set code_slot = object_id[index:] %}
              {{ code_slot  }}
            usercode: >-
              {{ range(1000, 9999) | random | int }}

    - alias: Decrement access count
      trigger:
        platform: state
        entity_id: sensor.frontdoor_statusreport
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set report = states.sensor.frontdoor_statusreport.state %}
            {% set a = report.split(';') %}
            {% if (a|length) == 3 and (a[2] | int > 0) %} 
               {{ (a[0] | int == 19) }}
            {% else %}
              {{ false }}
            {% endif %}
      action:
        - service: input_number.decrement
          data_template:
            entity_id: >-
              {% set report = states.sensor.frontdoor_statusreport.state %}
              {% set a = report.split(';') %}
              {{ 'input_number.frontdoor_accesscount_' + a[2] }}
